#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- with .Values.kyuubiConf.kyuubiEnv }}
  kyuubi-env.sh: |
    #!/usr/bin/env bash
    {{- tpl . $ | nindent 4 }}
  {{- end }}
  kyuubi-defaults.conf: |
    ## Helm chart provided Kyuubi configurations
    kyuubi.kubernetes.namespace={{ .Release.Namespace }}
    kyuubi.frontend.connection.url.use.hostname=false
    kyuubi.frontend.thrift.binary.bind.port={{ .Values.server.thriftBinary.port }}
    kyuubi.frontend.thrift.http.bind.port={{ .Values.server.thriftHttp.port }}
    kyuubi.frontend.rest.bind.port={{ .Values.server.rest.port }}
    kyuubi.frontend.mysql.bind.port={{ .Values.server.mysql.port }}
    kyuubi.frontend.protocols={{ include "kyuubi.frontend.protocols" . }}

    ## User provided Kyuubi configurations
    {{- with .Values.kyuubiConf.kyuubiDefaults }}
    {{- tpl . $ | nindent 4 }}
    {{- end }}
  {{- with .Values.kyuubiConf.log4j2 }}
  log4j2.xml: |
    {{- tpl . $ | nindent 4 }}
  {{- end }}
  {{- with .Values.kyuubiConf.extraFiles }}
  {{- range $key, $value := . }}
  {{ $key }}: |
    {{- tpl (printf "%v" $value) $ | nindent 4 }}
  {{- end }}
  {{- end }}
