name: Web UI

on:
  push:
    branches:
      - master
      - branch-*
  pull_request:
    branches:
      - master
      - branch-*

concurrency:
  group: web-ui-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  web-ui:
    name: Kyuubi Web UI check
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup npm
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: npm run coverage & build
        run: |
          cd ./kyuubi-server/web-ui
          npm install pnpm -g
          pnpm install
          pnpm run coverage
          pnpm run build
